#!/bin/sh

docker events --filter "image=$2" --filter "event=start"| \
while read line; do
  echo
  echo "Detected a container was launched on this host with image: $2"
  # Set the permissions on the container to access USB device
  /usr/local/bin/docker-swarm-usb-enable $1 $2
done
