version: '3.8'

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  cloudflared:
    image: cloudflare/cloudflared
    command: proxy-dns
    environment:
      TUNNEL_DNS_UPSTREAM: https://1.1.1.1/dns-query,https://1.0.0.1/dns-query,https://9.9.9.9/dns-query,https://149.112.112.9/dns-query
      TUNNEL_DNS_PORT: 5053
      TUNNEL_DNS_ADDRESS: 0.0.0.0
    networks:
      internal:
        ipv4_address: 172.30.10.2

  pihole:
    image: pihole/pihole
    environment:
      TZ: Europe/Amsterdam
      PIHOLE_DNS_: 172.30.10.2#5053
      WEBPASSWORD_FILE: /run/secrets/pihole-admin
    volumes:
      - etc-pihole:/etc/pihole/
      - etc-dnsmasq.d:/etc/dnsmasq.d/
      - etc-pihole-updatelists:/etc/pihole-updatelists/
    networks:
       - internal
       - infra-network_public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pihole.entrypoints=https"
        - "traefik.http.routers.pihole.tls=true"
        - "traefik.http.routers.pihole.tls.certresolver=letsencrypt"
        - "traefik.http.services.pihole.loadbalancer.server.port=80"

        - "traefik.tcp.routers.dns_tcp.rule=HostSNI(`*`)"
        - "traefik.tcp.routers.dns_tcp.entrypoints=dns-tcp"
        - "traefik.tcp.routers.dns_tcp.service=pihole"
        - "traefik.tcp.services.pihole.loadbalancer.server.port=53"

        - "traefik.udp.routers.dns_udp.entrypoints=dns-udp"
        - "traefik.udp.routers.dns_udp.service=pihole"
        - "traefik.udp.services.pihole.loadbalancer.server.port=53"
      mode: global
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: unless-stopped

networks:
  infra-network_public:
    external: true
  internal:
    ipam:
      config:
        - subnet: 172.30.10.0/29

volumes:
  etc-pihole:
  etc-dnsmasq.d:
  etc-pihole-updatelists:

secrets:
  pihole-admin:
    external: true

