http:
  routers:
    homeassistant:
      rule: "Host(`home.{{ env "DOMAIN" }}`)"
      entrypoints:
        - https
      service: homeassistant

  services:
    homeassistant:
      loadbalancer:
        servers:
          - url: "http://172.17.0.1:8123"

