http:
  routers:
    homeassistant:
      rule: 'Host(`home.{{ env "DOMAIN" }}`)'
      entrypoints:
        - https
      service: homeassistant
    dsm:
      rule: 'Host(`dsm.{{ env "DOMAIN" }}`)'
      entrypoints:
        - https
      service: dsm

  services:
    homeassistant:
      loadbalancer:
        servers:
          - url: "http://172.17.0.1:8123"
    dsm:
      loadbalancer:
        servers:
          - url: "http://192.168.1.20:5500"

